# Generated by Django 5.1.3 on 2024-12-29 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cou_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cou_id', models.IntegerField()),
                ('cou_abb', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_name', models.CharField(max_length=30)),
                ('cap_abb', models.CharField(max_length=10)),
                ('cou_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
    ]
